/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NooTest */

#ifndef _Included_NooTest
#define _Included_NooTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NooTest
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NooTest_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NooTest
 * Method:    hello_world
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NooTest_hello_1world
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
